[2022-10-26 13:33:10,827] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_raw_data.equipos_raw_create scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-26 13:33:10,846] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_raw_data.equipos_raw_create scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-26 13:33:10,846] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 13:33:10,847] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-10-26 13:33:10,847] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 13:33:10,889] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): equipos_raw_create> on 2022-09-01 00:00:00+00:00
[2022-10-26 13:33:10,896] {standard_task_runner.py:52} INFO - Started process 343 to run task
[2022-10-26 13:33:10,922] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_raw_data', 'equipos_raw_create', 'scheduled__2022-09-01T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/raw-dag.py', '--cfg-path', '/tmp/tmptpd4rb6d', '--error-file', '/tmp/tmpf36f8sya']
[2022-10-26 13:33:10,925] {standard_task_runner.py:80} INFO - Job 5: Subtask equipos_raw_create
[2022-10-26 13:33:11,134] {task_command.py:369} INFO - Running <TaskInstance: load_raw_data.equipos_raw_create scheduled__2022-09-01T00:00:00+00:00 [running]> on host b1681a16582a
[2022-10-26 13:33:11,602] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_raw_data
AIRFLOW_CTX_TASK_ID=equipos_raw_create
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-01T00:00:00+00:00
[2022-10-26 13:33:11,703] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 92, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 181, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 86, in get_conn
    conn = deepcopy(self.connection or self.get_connection(conn_id))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 430, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres-default` isn't defined
[2022-10-26 13:33:11,757] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=load_raw_data, task_id=equipos_raw_create, execution_date=20220901T000000, start_date=20221026T133310, end_date=20221026T133311
[2022-10-26 13:33:11,904] {standard_task_runner.py:97} ERROR - Failed to execute job 5 for task equipos_raw_create (The conn_id `postgres-default` isn't defined; 343)
[2022-10-26 13:33:11,924] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-10-26 13:33:12,219] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-10-26 14:27:29,250] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_raw_data.equipos_raw_create scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-26 14:27:29,356] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_raw_data.equipos_raw_create scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-26 14:27:29,356] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 14:27:29,357] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-10-26 14:27:29,357] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 14:27:29,432] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): equipos_raw_create> on 2022-09-01 00:00:00+00:00
[2022-10-26 14:27:29,437] {standard_task_runner.py:52} INFO - Started process 251 to run task
[2022-10-26 14:27:29,463] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_raw_data', 'equipos_raw_create', 'scheduled__2022-09-01T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/raw-dag.py', '--cfg-path', '/tmp/tmp3yiim4m7', '--error-file', '/tmp/tmpmx8632cc']
[2022-10-26 14:27:29,465] {standard_task_runner.py:80} INFO - Job 3: Subtask equipos_raw_create
[2022-10-26 14:27:29,778] {task_command.py:369} INFO - Running <TaskInstance: load_raw_data.equipos_raw_create scheduled__2022-09-01T00:00:00+00:00 [running]> on host d860ef10ab5f
[2022-10-26 14:27:30,593] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_raw_data
AIRFLOW_CTX_TASK_ID=equipos_raw_create
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-01T00:00:00+00:00
[2022-10-26 14:27:30,738] {base.py:68} INFO - Using connection ID 'postgres-default' for task execution.
[2022-10-26 14:27:30,763] {dbapi.py:208} INFO - Running statement: CREATE TABLE IF NOT EXISTS equipos_raw (equipo_id serial primary key,
                                                                                equipo varchar(100),
                                                                                sigla varchar(3));
                        , parameters: None
[2022-10-26 14:27:30,898] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=load_raw_data, task_id=equipos_raw_create, execution_date=20220901T000000, start_date=20221026T142729, end_date=20221026T142730
[2022-10-26 14:27:31,012] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-26 14:27:31,157] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-10-26 14:47:43,943] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_raw_data.equipos_raw_create scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-26 14:47:43,963] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_raw_data.equipos_raw_create scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-26 14:47:43,963] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 14:47:43,963] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-10-26 14:47:43,963] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 14:47:43,989] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): equipos_raw_create> on 2022-09-01 00:00:00+00:00
[2022-10-26 14:47:43,997] {standard_task_runner.py:52} INFO - Started process 278 to run task
[2022-10-26 14:47:44,005] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_raw_data', 'equipos_raw_create', 'scheduled__2022-09-01T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/raw-dag.py', '--cfg-path', '/tmp/tmpzda5e3_7', '--error-file', '/tmp/tmphuu3qiyj']
[2022-10-26 14:47:44,008] {standard_task_runner.py:80} INFO - Job 6: Subtask equipos_raw_create
[2022-10-26 14:47:44,214] {task_command.py:369} INFO - Running <TaskInstance: load_raw_data.equipos_raw_create scheduled__2022-09-01T00:00:00+00:00 [running]> on host 4af2e895db31
[2022-10-26 14:47:44,572] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_raw_data
AIRFLOW_CTX_TASK_ID=equipos_raw_create
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-01T00:00:00+00:00
[2022-10-26 14:47:44,676] {base.py:68} INFO - Using connection ID 'postgres-default' for task execution.
[2022-10-26 14:47:44,682] {dbapi.py:208} INFO - Running statement: CREATE TABLE IF NOT EXISTS equipos_raw (equipo_id serial primary key,
                                                                                equipo varchar(100),
                                                                                sigla varchar(3));
                        , parameters: None
[2022-10-26 14:47:44,761] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=load_raw_data, task_id=equipos_raw_create, execution_date=20220901T000000, start_date=20221026T144743, end_date=20221026T144744
[2022-10-26 14:47:44,803] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-26 14:47:44,890] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
