[2022-10-26 13:33:11,050] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_raw_data.generos_raw_create scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-26 13:33:11,088] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_raw_data.generos_raw_create scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-26 13:33:11,089] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 13:33:11,089] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-10-26 13:33:11,089] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 13:33:11,153] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): generos_raw_create> on 2022-09-01 00:00:00+00:00
[2022-10-26 13:33:11,163] {standard_task_runner.py:52} INFO - Started process 346 to run task
[2022-10-26 13:33:11,177] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_raw_data', 'generos_raw_create', 'scheduled__2022-09-01T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/raw-dag.py', '--cfg-path', '/tmp/tmpjj8hrgac', '--error-file', '/tmp/tmpqvk0inj2']
[2022-10-26 13:33:11,188] {standard_task_runner.py:80} INFO - Job 3: Subtask generos_raw_create
[2022-10-26 13:33:11,377] {task_command.py:369} INFO - Running <TaskInstance: load_raw_data.generos_raw_create scheduled__2022-09-01T00:00:00+00:00 [running]> on host b1681a16582a
[2022-10-26 13:33:11,732] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_raw_data
AIRFLOW_CTX_TASK_ID=generos_raw_create
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-01T00:00:00+00:00
[2022-10-26 13:33:12,054] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 92, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 181, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 86, in get_conn
    conn = deepcopy(self.connection or self.get_connection(conn_id))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 430, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres-default` isn't defined
[2022-10-26 13:33:12,074] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=load_raw_data, task_id=generos_raw_create, execution_date=20220901T000000, start_date=20221026T133311, end_date=20221026T133312
[2022-10-26 13:33:12,135] {standard_task_runner.py:97} ERROR - Failed to execute job 3 for task generos_raw_create (The conn_id `postgres-default` isn't defined; 346)
[2022-10-26 13:33:12,206] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-10-26 13:33:12,680] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-10-26 14:27:29,693] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_raw_data.generos_raw_create scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-26 14:27:29,735] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_raw_data.generos_raw_create scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-26 14:27:29,735] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 14:27:29,735] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-10-26 14:27:29,736] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 14:27:29,788] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): generos_raw_create> on 2022-09-01 00:00:00+00:00
[2022-10-26 14:27:29,800] {standard_task_runner.py:52} INFO - Started process 253 to run task
[2022-10-26 14:27:29,817] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_raw_data', 'generos_raw_create', 'scheduled__2022-09-01T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/raw-dag.py', '--cfg-path', '/tmp/tmpx9zutiw5', '--error-file', '/tmp/tmp7v1gthnl']
[2022-10-26 14:27:29,821] {standard_task_runner.py:80} INFO - Job 2: Subtask generos_raw_create
[2022-10-26 14:27:30,613] {task_command.py:369} INFO - Running <TaskInstance: load_raw_data.generos_raw_create scheduled__2022-09-01T00:00:00+00:00 [running]> on host d860ef10ab5f
[2022-10-26 14:27:31,113] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_raw_data
AIRFLOW_CTX_TASK_ID=generos_raw_create
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-01T00:00:00+00:00
[2022-10-26 14:27:31,137] {base.py:68} INFO - Using connection ID 'postgres-default' for task execution.
[2022-10-26 14:27:31,150] {dbapi.py:208} INFO - Running statement: CREATE TABLE IF NOT EXISTS generos_raw (genero_id serial primary key,
                                                                                genero varchar(1));
                        , parameters: None
[2022-10-26 14:27:31,276] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=load_raw_data, task_id=generos_raw_create, execution_date=20220901T000000, start_date=20221026T142729, end_date=20221026T142731
[2022-10-26 14:27:31,341] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-26 14:27:31,422] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-10-26 14:47:44,120] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_raw_data.generos_raw_create scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-26 14:47:44,166] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_raw_data.generos_raw_create scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-26 14:47:44,166] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 14:47:44,167] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-10-26 14:47:44,167] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 14:47:44,201] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): generos_raw_create> on 2022-09-01 00:00:00+00:00
[2022-10-26 14:47:44,213] {standard_task_runner.py:52} INFO - Started process 281 to run task
[2022-10-26 14:47:44,245] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_raw_data', 'generos_raw_create', 'scheduled__2022-09-01T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/raw-dag.py', '--cfg-path', '/tmp/tmp77xfa6nj', '--error-file', '/tmp/tmpgx6n8in1']
[2022-10-26 14:47:44,252] {standard_task_runner.py:80} INFO - Job 5: Subtask generos_raw_create
[2022-10-26 14:47:44,404] {task_command.py:369} INFO - Running <TaskInstance: load_raw_data.generos_raw_create scheduled__2022-09-01T00:00:00+00:00 [running]> on host 4af2e895db31
[2022-10-26 14:47:44,651] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_raw_data
AIRFLOW_CTX_TASK_ID=generos_raw_create
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-01T00:00:00+00:00
[2022-10-26 14:47:44,674] {base.py:68} INFO - Using connection ID 'postgres-default' for task execution.
[2022-10-26 14:47:44,681] {dbapi.py:208} INFO - Running statement: CREATE TABLE IF NOT EXISTS generos_raw (genero_id serial primary key,
                                                                                genero varchar(1));
                        , parameters: None
[2022-10-26 14:47:44,722] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=load_raw_data, task_id=generos_raw_create, execution_date=20220901T000000, start_date=20221026T144744, end_date=20221026T144744
[2022-10-26 14:47:44,767] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-26 14:47:44,847] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-10-26 17:10:49,156] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_raw_data.generos_raw_create scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-26 17:10:49,207] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_raw_data.generos_raw_create scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-26 17:10:49,207] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 17:10:49,207] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-10-26 17:10:49,207] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 17:10:49,303] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): generos_raw_create> on 2022-09-01 00:00:00+00:00
[2022-10-26 17:10:49,330] {standard_task_runner.py:52} INFO - Started process 250 to run task
[2022-10-26 17:10:49,477] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_raw_data', 'generos_raw_create', 'scheduled__2022-09-01T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/raw-dag.py', '--cfg-path', '/tmp/tmpluq_x2zx', '--error-file', '/tmp/tmpmmxeeh9h']
[2022-10-26 17:10:49,483] {standard_task_runner.py:80} INFO - Job 6: Subtask generos_raw_create
[2022-10-26 17:10:50,343] {task_command.py:369} INFO - Running <TaskInstance: load_raw_data.generos_raw_create scheduled__2022-09-01T00:00:00+00:00 [running]> on host 553edc2a1daa
[2022-10-26 17:10:51,370] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_raw_data
AIRFLOW_CTX_TASK_ID=generos_raw_create
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-01T00:00:00+00:00
[2022-10-26 17:10:51,416] {base.py:68} INFO - Using connection ID 'postgres-default' for task execution.
[2022-10-26 17:10:51,429] {dbapi.py:208} INFO - Running statement: CREATE TABLE IF NOT EXISTS generos_raw (genero_id serial primary key,
                                                                                genero varchar(1));
                        , parameters: None
[2022-10-26 17:10:51,588] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=load_raw_data, task_id=generos_raw_create, execution_date=20220901T000000, start_date=20221026T171049, end_date=20221026T171051
[2022-10-26 17:10:51,652] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-26 17:10:51,958] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
