[2022-10-26 14:30:50,171] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dbt_dim.deportistas_dim scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-26 14:30:50,211] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dbt_dim.deportistas_dim scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-26 14:30:50,211] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 14:30:50,211] {taskinstance.py:1357} INFO - Starting attempt 3 of 4
[2022-10-26 14:30:50,211] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 14:30:50,247] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): deportistas_dim> on 2022-09-01 00:00:00+00:00
[2022-10-26 14:30:50,252] {standard_task_runner.py:52} INFO - Started process 398 to run task
[2022-10-26 14:30:50,257] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dbt_dim', 'deportistas_dim', 'scheduled__2022-09-01T00:00:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dim.py', '--cfg-path', '/tmp/tmpmz5xgaxo', '--error-file', '/tmp/tmpcopiuapx']
[2022-10-26 14:30:50,259] {standard_task_runner.py:80} INFO - Job 20: Subtask deportistas_dim
[2022-10-26 14:30:50,372] {task_command.py:369} INFO - Running <TaskInstance: dbt_dim.deportistas_dim scheduled__2022-09-01T00:00:00+00:00 [running]> on host d860ef10ab5f
[2022-10-26 14:30:50,657] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dbt_dim
AIRFLOW_CTX_TASK_ID=deportistas_dim
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-01T00:00:00+00:00
[2022-10-26 14:30:50,659] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-10-26 14:30:50,661] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'cd /opt/dbt/oly_dbt && dbt run --select +deportistas_dim']
[2022-10-26 14:30:50,689] {subprocess.py:85} INFO - Output:
[2022-10-26 14:30:53,754] {subprocess.py:92} INFO - [0m14:30:53  Running with dbt=1.3.0
[2022-10-26 14:30:53,915] {subprocess.py:92} INFO - [0m14:30:53  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2022-10-26 14:30:53,915] {subprocess.py:92} INFO - There are 1 unused configuration paths:
[2022-10-26 14:30:53,915] {subprocess.py:92} INFO - - models.oly_dbt.example
[2022-10-26 14:30:53,915] {subprocess.py:92} INFO - 
[2022-10-26 14:30:53,934] {subprocess.py:92} INFO - [0m14:30:53  Found 2 models, 0 tests, 0 snapshots, 0 analyses, 289 macros, 0 operations, 0 seed files, 0 sources, 0 exposures, 0 metrics
[2022-10-26 14:30:53,936] {subprocess.py:92} INFO - [0m14:30:53
[2022-10-26 14:30:54,023] {subprocess.py:92} INFO - [0m14:30:54  Concurrency: 4 threads (target='dev')
[2022-10-26 14:30:54,023] {subprocess.py:92} INFO - [0m14:30:54
[2022-10-26 14:30:54,029] {subprocess.py:92} INFO - [0m14:30:54  1 of 1 START sql view model public.deportistas_dim ............................. [RUN]
[2022-10-26 14:30:54,177] {subprocess.py:92} INFO - [0m14:30:54  1 of 1 OK created sql view model public.deportistas_dim ........................ [[32mCREATE VIEW[0m in 0.15s]
[2022-10-26 14:30:54,244] {subprocess.py:92} INFO - [0m14:30:54
[2022-10-26 14:30:54,245] {subprocess.py:92} INFO - [0m14:30:54  Finished running 1 view model in 0 hours 0 minutes and 0.31 seconds (0.31s).
[2022-10-26 14:30:54,255] {subprocess.py:92} INFO - [0m14:30:54
[2022-10-26 14:30:54,256] {subprocess.py:92} INFO - [0m14:30:54  [32mCompleted successfully[0m
[2022-10-26 14:30:54,256] {subprocess.py:92} INFO - [0m14:30:54
[2022-10-26 14:30:54,257] {subprocess.py:92} INFO - [0m14:30:54  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2022-10-26 14:30:55,342] {subprocess.py:96} INFO - Command exited with return code 0
[2022-10-26 14:30:55,399] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dbt_dim, task_id=deportistas_dim, execution_date=20220901T000000, start_date=20221026T143050, end_date=20221026T143055
[2022-10-26 14:30:55,438] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-26 14:30:55,510] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-10-26 15:13:10,766] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dbt_dim.deportistas_dim scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-26 15:13:10,795] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dbt_dim.deportistas_dim scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-26 15:13:10,796] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 15:13:10,796] {taskinstance.py:1357} INFO - Starting attempt 3 of 4
[2022-10-26 15:13:10,797] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 15:13:10,820] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): deportistas_dim> on 2022-09-01 00:00:00+00:00
[2022-10-26 15:13:10,825] {standard_task_runner.py:52} INFO - Started process 837 to run task
[2022-10-26 15:13:10,831] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dbt_dim', 'deportistas_dim', 'scheduled__2022-09-01T00:00:00+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dim.py', '--cfg-path', '/tmp/tmpitq_ke62', '--error-file', '/tmp/tmpmfa5uwut']
[2022-10-26 15:13:10,833] {standard_task_runner.py:80} INFO - Job 23: Subtask deportistas_dim
[2022-10-26 15:13:10,919] {task_command.py:369} INFO - Running <TaskInstance: dbt_dim.deportistas_dim scheduled__2022-09-01T00:00:00+00:00 [running]> on host 4af2e895db31
[2022-10-26 15:13:11,097] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dbt_dim
AIRFLOW_CTX_TASK_ID=deportistas_dim
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-01T00:00:00+00:00
[2022-10-26 15:13:11,099] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-10-26 15:13:11,100] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'cd /opt/dbt/oly_dbt/models/dim_tables && dbt run --select +deportistas_dim']
[2022-10-26 15:13:11,120] {subprocess.py:85} INFO - Output:
[2022-10-26 15:13:15,943] {subprocess.py:92} INFO - [0m15:13:15  Encountered an error while reading the project:
[2022-10-26 15:13:15,944] {subprocess.py:92} INFO - [0m15:13:15    ERROR: Runtime Error
[2022-10-26 15:13:15,944] {subprocess.py:92} INFO -   Could not find profile named 'oly_dbt'
[2022-10-26 15:13:16,040] {subprocess.py:92} INFO - [0m15:13:16  Encountered an error:
[2022-10-26 15:13:16,040] {subprocess.py:92} INFO - Runtime Error
[2022-10-26 15:13:16,040] {subprocess.py:92} INFO -   Could not run dbt
[2022-10-26 15:13:16,307] {subprocess.py:96} INFO - Command exited with return code 2
[2022-10-26 15:13:16,332] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2022-10-26 15:13:16,338] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_dim, task_id=deportistas_dim, execution_date=20220901T000000, start_date=20221026T151310, end_date=20221026T151316
[2022-10-26 15:13:16,363] {standard_task_runner.py:97} ERROR - Failed to execute job 23 for task deportistas_dim (Bash command failed. The command returned a non-zero exit code 2.; 837)
[2022-10-26 15:13:16,372] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-10-26 15:13:16,412] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
