[2022-10-26 15:14:17,306] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dbt_dim.eventos_dim scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-26 15:14:17,326] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dbt_dim.eventos_dim scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-26 15:14:17,327] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 15:14:17,327] {taskinstance.py:1357} INFO - Starting attempt 4 of 4
[2022-10-26 15:14:17,327] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 15:14:17,355] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): eventos_dim> on 2022-09-01 00:00:00+00:00
[2022-10-26 15:14:17,360] {standard_task_runner.py:52} INFO - Started process 868 to run task
[2022-10-26 15:14:17,364] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dbt_dim', 'eventos_dim', 'scheduled__2022-09-01T00:00:00+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dim.py', '--cfg-path', '/tmp/tmp650tto_k', '--error-file', '/tmp/tmpigw4w6d3']
[2022-10-26 15:14:17,366] {standard_task_runner.py:80} INFO - Job 25: Subtask eventos_dim
[2022-10-26 15:14:17,451] {task_command.py:369} INFO - Running <TaskInstance: dbt_dim.eventos_dim scheduled__2022-09-01T00:00:00+00:00 [running]> on host 4af2e895db31
[2022-10-26 15:14:17,561] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dbt_dim
AIRFLOW_CTX_TASK_ID=eventos_dim
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-01T00:00:00+00:00
[2022-10-26 15:14:17,562] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-10-26 15:14:17,563] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'cd /opt/dbt/oly_dbt/models/dim_tables && dbt run --select +eventos_dim']
[2022-10-26 15:14:17,575] {subprocess.py:85} INFO - Output:
[2022-10-26 15:14:21,489] {subprocess.py:92} INFO - [0m15:14:21  Encountered an error while reading the project:
[2022-10-26 15:14:21,489] {subprocess.py:92} INFO - [0m15:14:21    ERROR: Runtime Error
[2022-10-26 15:14:21,490] {subprocess.py:92} INFO -   Could not find profile named 'oly_dbt'
[2022-10-26 15:14:21,508] {subprocess.py:92} INFO - [0m15:14:21  Encountered an error:
[2022-10-26 15:14:21,508] {subprocess.py:92} INFO - Runtime Error
[2022-10-26 15:14:21,508] {subprocess.py:92} INFO -   Could not run dbt
[2022-10-26 15:14:21,823] {subprocess.py:96} INFO - Command exited with return code 2
[2022-10-26 15:14:21,868] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2022-10-26 15:14:21,878] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=dbt_dim, task_id=eventos_dim, execution_date=20220901T000000, start_date=20221026T151417, end_date=20221026T151421
[2022-10-26 15:14:21,919] {standard_task_runner.py:97} ERROR - Failed to execute job 25 for task eventos_dim (Bash command failed. The command returned a non-zero exit code 2.; 868)
[2022-10-26 15:14:21,967] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-10-26 15:14:22,034] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
