[2022-10-26 13:44:07,995] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dbt_dim.install_dbt scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-26 13:44:08,016] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dbt_dim.install_dbt scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-26 13:44:08,016] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 13:44:08,017] {taskinstance.py:1357} INFO - Starting attempt 4 of 4
[2022-10-26 13:44:08,017] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 13:44:08,066] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): install_dbt> on 2022-09-01 00:00:00+00:00
[2022-10-26 13:44:08,071] {standard_task_runner.py:52} INFO - Started process 627 to run task
[2022-10-26 13:44:08,074] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dbt_dim', 'install_dbt', 'scheduled__2022-09-01T00:00:00+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dim.py', '--cfg-path', '/tmp/tmp1xkqvjds', '--error-file', '/tmp/tmp09hkoa82']
[2022-10-26 13:44:08,075] {standard_task_runner.py:80} INFO - Job 28: Subtask install_dbt
[2022-10-26 13:44:08,142] {task_command.py:369} INFO - Running <TaskInstance: dbt_dim.install_dbt scheduled__2022-09-01T00:00:00+00:00 [running]> on host b1681a16582a
[2022-10-26 13:44:08,240] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dbt_dim
AIRFLOW_CTX_TASK_ID=install_dbt
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-01T00:00:00+00:00
[2022-10-26 13:44:08,242] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-10-26 13:44:08,245] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'sudo su *** && pip install dbt-postgres && pip install --upgrade Jinja2==3.0.3']
[2022-10-26 13:44:08,255] {subprocess.py:85} INFO - Output:
[2022-10-26 13:44:08,294] {subprocess.py:92} INFO - 
[2022-10-26 13:44:08,294] {subprocess.py:92} INFO - [31mYou are running pip as root. Please use '***' user to run pip![0m
[2022-10-26 13:44:08,294] {subprocess.py:92} INFO - 
[2022-10-26 13:44:08,295] {subprocess.py:92} INFO - [33mSee: https://***.apache.org/docs/docker-stack/build.html#adding-a-new-pypi-package[0m
[2022-10-26 13:44:08,295] {subprocess.py:92} INFO - 
[2022-10-26 13:44:08,295] {subprocess.py:96} INFO - Command exited with return code 1
[2022-10-26 13:44:08,316] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-10-26 13:44:08,320] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=dbt_dim, task_id=install_dbt, execution_date=20220901T000000, start_date=20221026T134407, end_date=20221026T134408
[2022-10-26 13:44:08,338] {standard_task_runner.py:97} ERROR - Failed to execute job 28 for task install_dbt (Bash command failed. The command returned a non-zero exit code 1.; 627)
[2022-10-26 13:44:08,367] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-10-26 13:44:08,423] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
